### ISSUE TITLE
Error: no argument named 'default_sources'

### ISSUE THREAD

**Issue by gummybears** [jessedoyle/duktape.cr#62]
I am getting the following error
```
crystal: 0.34.0

license: MIT

dependencies:

  sass:
    github: straight-shoota/sass.cr

  coffee-script:
    github: jessedoyle/coffee-script
```

```
In lib/duktape/src/duktape/log.cr:10:5

 10 | Log.setup_from_env(
          ^-------------
Error: no argument named 'default_sources'

Matches are:
 - Log.setup_from_env(*, builder : Log::Builder = Log.builder, level = ENV.fetch("CRYSTAL_LOG_LEVEL", "INFO"), sources = ENV.fetch("CRYSTAL_LOG_SOURCES", ""), backend = Log::IOBackend.new)
```

I can use your shard by commenting out line 11 of log.cr
```
default_sources: ENV.fetch("LOG_SOURCES", "duktape.*"),
```

**Comment by jessedoyle** [comment]
Hi @gummybears, thanks for using `duktape.cr`!

It looks like you're using Crystal 0.34.0, which isn't the current latest release of Crystal.

Crystal core made a few breaking changes with respect to `Log.setup_from_env`, see https://github.com/crystal-lang/crystal/pull/9145 and https://github.com/crystal-lang/crystal/pull/9240.

If you update to the current latest version of Crystal (0.35.1 at the time of this writing), does the issue resolve?

Thanks

**Comment by gummybears** [comment]
I cannot upgrade to Crystal 0.35.1 at the moment. Can you confirm the upgrade to Crystal 0.35.1 resolves this issue ?

**Comment by jessedoyle** [comment]
Hi @gummybears - I'm not getting any errors on Crystal 0.35.1.

If you're running on Crystal 0.34, you'll likely want to lock `duktape.cr` to version `0.20.0` as that was the release that introduced compatibility with Crystal 0.34.

i.e.

```yaml
dependencies:
  duktape:
    github: jessedoyle/duktape.cr
    version: 0.20.0
```
